<?php
namespace app\components\fileinput;

use yii\helpers\Html;

class Fileinput extends \yii\base\Widget
{

    public $options;
    public $model;
    public $attribute;

    public function init()
    {
        $this->options['multiple'] = true;
        if(!isset($this->options['class'])) {
            $this->options['class'] = '';
        }
        $this->options['class'] .= ' fl-js-input fl-js-input-main';
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $input = Html::activeFileInput($this->model, $this->attribute, $this->options);

        return $this->render('fileinput', [
            'input' => $input,
            'model' => $this->model
        ]);
    }
}